name: setup flow
description: ''

branding:
  icon: loader
  color: purple

inputs:
  workspace:
    description: folder to run the flow in
    required: true

outputs:
  test:
    value: ${{ fromJson(steps.workspace-info.outputs.json).commands.test }}
    description: the test command from the workspace.json file

  build:
    value: ${{ fromJson(steps.workspace-info.outputs.json).commands.build }}
    description: the build command from the workspace.json file

  publish:
    value: ${{ fromJson(steps.workspace-info.outputs.json).commands.publish }}
    description: the publish command from the workspace.json file

runs:
  using: composite

  steps:
    - name: read workspace
      id: workspace-info
      working-directory: ${{ inputs.workspace }}
      shell: bash
      run: |
        echo "json=$(cat workspace.json)" >> $GITHUB_OUTPUT

    - name: setup runtime
      uses: ${{ fromJson(steps.workspace-info.outputs.json).image.uses }}
      with: ${{ fromJson(fromJson(steps.workspace-info.outputs.json).image.with) }}

    - name: Setup cache
      uses: actions/cache@v3
      id: cache
      with:
        key: ${{ hashFiles(fromJson(steps.workspace-info.outputs.json).cache.key) }}
        path: fromJson(steps.workspace-info.outputs.json).cache.path

    - name: Install deps
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      shell: bash
      working-directory: ${{ inputs.workspace }}
      run: ${{ fromJson(steps.workspace-info.outputs.json).commands.install }}
