name: 🚀

on:
  pull_request:
    types: ['closed']

jobs:
  only-changed:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest

    outputs:
      projects: ${{ steps.diff.outputs.result }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find projects which have changed
        uses: ./.github/actions/diff
        id: diff

  test:
    runs-on: ubuntu-latest
    needs: only-changed

    strategy:
      matrix:
        project: ${{ fromJSON(needs.only-changed.outputs.projects) }}
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare repository
        uses: ./.github/actions/prepare
        with:
          project: ${{ matrix.project }}

      - name: Build
        working-directory: ${{ matrix.project }}
        run: yarn build

      - name: Deploy
        working-directory: ${{ matrix.project }}
        run: yarn deploy
