name: HashFiles

on:
  push:
    branches:
      - main

jobs:
  test-hash:
    strategy:
      matrix:
        workspace: ['foo', 'bar']

    uses: ./.github/workflows/wf.yml
    with:
      name: ${{ matrix.workspace }}
    secrets: inherit
