name: HashFiles

on:
  push:
    branches:
      - main

jobs:
  test-hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - run: echo "${{ hashFiles(format('{0}/**', 'foo/')) }}"
