name: Bug report

on:
  push:
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-node@v3
    
      - run: |
          echo '{ "scripts": { "foo": "echo foo;" } }' > package.json
          
      - run: |
          yarn foo
          
      - uses: actions/github-script@v6
        with:
          script: |
            const util = require('util');
            const bash = util.promisify(require('child_process').exec);

            const std = await bash(`yarn foo`, { cwd: process.cwd() })

            await core.summary
              .addCodeBlock(std, 'json')
              .write()

