name: Bug report

on:
  push:
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-node@v3
    
      - run: |
          echo '{ "scripts": { "foo": "echo foo;" } }' > package.json
          
      - run: |
          yarn foo
