name: 🧪

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Failing task
        run: |
          bash -c "echo subshell"
                    
          echo "main exit code: $?"
          exit 0
