name: 🧪

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

env: ${{ secrets }}

jobs:
  only-changed:
    runs-on: ubuntu-latest

    outputs:
      workspaces: ${{ steps.diff.outputs.result }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: find workspaces which have changed
        uses: ./.github/actions/diff
        id: diff

  test:
    runs-on: ubuntu-latest
    needs: only-changed

    # should have at least one workspace to run (cannot have empty matrix)
    if: fromJSON(needs.only-changed.outputs.workspaces)[0] != null

    strategy:
      matrix:
        workspace: ${{ fromJSON(needs.only-changed.outputs.workspaces) }}
      fail-fast: false

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - uses: jdx/mise-action@v2
        with:
          experimental: true
          working_directory: ${{ matrix.workspace }}

      - uses: actions/cache@v4
        id: cache
        with:
          key: ${{ env.CI_CACHE_KEY }}
          path: ${{ env.CI_CACHE_PATH }}

      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ${{ matrix.workspace }}
        run: mise tasks run install

      - name: run tests
        working-directory: ${{ matrix.workspace }}
        run: mise tasks run test

      - name: try building
        working-directory: ${{ matrix.workspace }}
        run: mise tasks run build
