name: 🧪
run-name: 🧪 (${{ inputs.env-name }})

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      env-name:
        default: 'staging'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version-file: nope/.node-version
