name: 🧪

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Failing task
        run: |
          bash -c "\
            echo 'in subshell'; \
            false; \
            echo 'capture error here:' $?; \
            exit 0; \
          "
                    
          echo "main exit code: $?"
          exit 0
