name: 🧪

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

env: ${{ secrets }}

jobs:
  only-changed:
    runs-on: ubuntu-latest

    outputs:
      workspaces: ${{ steps.diff.outputs.result }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find workspaces which have changed
        uses: ./.github/actions/monorepo-diff
        id: diff

  test:
    runs-on: ubuntu-latest
    needs: only-changed

    # should have at least one workspace to run (cannot have empty matrix)
    if: fromJSON(needs.only-changed.outputs.workspaces)[0] != null

    strategy:
      matrix:
        workspace: ${{ fromJSON(needs.only-changed.outputs.workspaces) }}
      fail-fast: false

    steps:
      - name: checkout workspace
        uses: actions/checkout@v3

      - name: prepare workspace
        id: setup
        uses: ./.github/actions/prepare-workspace
        with:
          workspace: ${{ matrix.workspace }}

      - name: Run tests
        working-directory: ${{ matrix.workspace }}
        run: ${{ steps.setup.outputs.test }}

      - name: Try build
        working-directory: ${{ matrix.workspace }}
        run: ${{ steps.setup.outputs.build }}
